spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.100.95.147:3306/studly?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: sgzxkt
      password: sgzxkt2020...
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        stat-view-servlet:
          allow: 127.0.0.1
  jpa:
    open-in-view: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        max_fetch_depth: 1
#        ddl-auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


mybatis:
   mapperLocations: classpath:/mapper/*.xml
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  appid: wx1411ecdfc3c6e585
  sercetkey: aaebab80b3d04901b8ce737b71699548
  merappid: xx
  merid: xx
  mername: xx
  merKey: xx
  notifyurl: http://xxxxxxx/payBack/xcxNotify
  loadpath: /home/static/html/
  showpath: http://xxxxxxx/html/




